package com.station226.league;


public class StaticUtilities {
	public static String getChampionName(int championId){
		switch(championId){
		case 412:
			return "Thresh";
		case 266:
			return "Aatrox";
		case 23:
			return "Tryndamere";
		case 79:
			return "Gragas";
		case 69:
			return "Cassiopeia";
		case 13:
			return "Ryze";
		case 78:
			return "Poppy";
		case 14:
			return "Sion";
		case 1:
			return "Annie";
		case 111:
			return "Nautilus";
		case 43:
			return "Karma";
		case 99:
			return "Lux";
		case 103:
			return "Ahri";
		case 2:
			return "Olaf";
		case 112:
			return "Viktor";
		case 34:
			return "Anivia";
		case 86:
			return "Garen";
		case 27:
			return "Singed";
		case 127:
			return "Lissandra";
		case 57:
			return "Maokai";
		case 25:
			return "Morgana";
		case 28:
			return "Evelynn";
		case 105:
			return "Fizz";
		case 238:
			return "Zed";
		case 74:
			return "Heimerdinger";
		case 68:
			return "Rumble";
		case 37:
			return "Sona";
		case 82:
			return "Mordekaiser";
		case 96:
			return "KogMaw";
		case 55:
			return "Katarina";
		case 117:
			return "Lulu";
		case 22:
			return "Ashe";
		case 30:
			return "Karthus";
		case 12:
			return "Alistar";
		case 122:
			return "Darius";
		case 67:
			return "Vayne";
		case 77:
			return "Udyr";
		case 110:
			return "Varus";
		case 89:
			return "Leona";
		case 126:
			return "Jayce";
		case 134:
			return "Syndra";
		case 80:
			return "Pantheon";
		case 92:
			return "Riven";
		case 121:
			return "Khazix";
		case 42:
			return "Corki";
		case 51:
			return "Caitlyn";
		case 76:
			return "Nidalee";
		case 85:
			return "Kennen";
		case 3:
			return "Galio";
		case 45:
			return "Veigar";
		case 104:
			return "Graves";
		case 90:
			return "Malzahar";
		case 254:
			return "Vi";
		case 10:
			return "Kayle";
		case 39:
			return "Irelia";
		case 64:
			return "LeeSin";
		case 60:
			return "Elise";
		case 106:
			return "Volibear";
		case 20:
			return "Nunu";
		case 4:
			return "TwistedFate";
		case 24:
			return "Jax";
		case 102:
			return "Shyvana";
		case 36:
			return "DrMundo";
		case 63:
			return "Brand";
		case 131:
			return "Diana";
		case 113:
			return "Sejuani";
		case 8:
			return "Vladimir";
		case 154:
			return "Zac";
		case 133:
			return "Quinn";
		case 84:
			return "Akali";
		case 18:
			return "Tristana";
		case 120:
			return "Hecarim";
		case 15:
			return "Sivir";
		case 236:
			return "Lucian";
		case 107:
			return "Rengar";
		case 19:
			return "Warwick";
		case 72:
			return "Skarner";
		case 54:
			return "Malphite";
		case 157:
			return "Yasuo";
		case 101:
			return "Xerath";
		case 17:
			return "Teemo";
		case 75:
			return "Nasus";
		case 58:
			return "Renekton";
		case 119:
			return "Draven";
		case 35:
			return "Shaco";
		case 50:
			return "Swain";
		case 115:
			return "Ziggs";
		case 40:
			return "Janna";
		case 91:
			return "Talon";
		case 61:
			return "Orianna";
		case 9:
			return "FiddleSticks";
		case 114:
			return "Fiora";
		case 31:
			return "Chogath";
		case 33:
			return "Rammus";
		case 7:
			return "Leblanc";
		case 26:
			return "Zilean";
		case 16:
			return "Soraka";
		case 56:
			return "Nocturne";
		case 222:
			return "Jinx";
		case 83:
			return "Yorick";
		case 6:
			return "Urgot";
		case 21:
			return "MissFortune";
		case 62:
			return "MonkeyKing";
		case 53:
			return "Blitzcrank";
		case 98:
			return "Shen";
		case 5:
			return "XinZhao";
		case 29:
			return "Twitch";
		case 11:
			return "MasterYi";
		case 44:
			return "Taric";
		case 32:
			return "Amumu";
		case 41:
			return "Gangplank";
		case 48:
			return "Trundle";
		case 38:
			return "Kassadin";
		case 161:
			return "Velkoz";
		case 143:
			return "Zyra";
		case 267:
			return "Nami";
		case 59:
			return "JarvanIV";
		case 81:
			return "Ezreal";
		default:
			return "Not Found";
		}
	}
}
